#!lisp.sh
;Comment
;Comment
;Comment
'Symbol
'Symbol
'Symbol
;'Symbol
; A comment
;'"Not a comment"
;'"Not a comment"
\;; Also not a comment
\; But this is
'\97; Decimal character constant
'\97"Now it's a symbol"
'\097; Bad octal character constant
'\065; Good octal character constant
'\x35; Hex character constant
'\x35z; Bad hex character constant
'"" ; comment after expression
'( ; comment in expression 
())
